# Loading Data In Python Through SciKit Learn And Performing Basic Operations On it.

## Importing The value

In [1]:
import pandas as pd 
data = pd.read_csv("student_scores.csv")
data.head(10)

     name  hours  score gender grades class
0   Aarav    NaN     76      M      A    9A
1    Riya    5.0     62    NaN    NaN    9B
2   Kabir   10.0     88      M      A   10A
3    Sana    4.0     55      F      C    9A
4  Vivaan    7.0     72      M      B   10B
5  Ishita    6.0     64      F      B    9C
6   Rohan    3.0     48      M      D    9B
7   Meera    9.0     90      F      A   11A
8  Aditya    2.0     38      M      F    9C
9   Kavya   11.0     93      F      A   12A

# Performing Operations.

In [2]:
import pandas as pd 
data = pd.read_csv("student_scores.csv")
data.head(10)
print('Columns:',data.columns.tolist())
print(' Info:')
print(data.info())
print(' Describe:')
display(data.describe())
print("Null Values: ")
print(data.isnull().sum())

Columns: ['name', 'hours', 'score', 'gender', 'grades', 'class']
 Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    92 non-null     object
 1   hours   91 non-null     float64
 2   score   92 non-null     int64
 3   gender  91 non-null     object
 4   grades  91 non-null     object
 5   class   92 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.4+ KB
None
 Describe:

           hours      score
count  91.000000  92.000000
mean    6.494505  68.836957
std     2.272412  15.692286
min     2.000000  35.000000
25%     5.000000  57.000000
50%     7.000000  70.000000
75%     8.000000  82.000000
max    11.000000  94.000000

Null Values:
name      0
hours     1
score     0
gender    1
grades    1
class     0
dtype: int64

## Filling Up The Missing Values with mean

In [9]:
import pandas as pd 
data = pd.read_csv("student_scores.csv")
print(data.isnull().sum())
data["score"]=data["score"].fillna(data["score"].mean())
print(data)

name      0
hours     0
score     3
gender    0
grades    0
class     0
dtype: int64
       name  hours      score gender grades class
0     Aarav     10  76.000000      M      A    9A
1      Riya      5  68.662921      F      A    9B
2     Kabir     10  68.662921      M      A   10A
3      Sana      4  55.000000      F      C    9A
4    Vivaan      7  68.662921      M      B   10B
..      ...    ...        ...    ...    ...   ...
87   Prisha      4  52.000000      F      C    9A
88     Neil     10  88.000000      M      A   12C
89    Rutvi      7  73.000000      F      B   10A
90  Harshit      5  57.000000      M      C    9B
91   Vritti      8  81.000000      F      A   11B

[92 rows x 6 columns]

# Encoding

## Label 1

In [13]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd 
data = pd.read_csv("student_scores.csv")
le = LabelEncoder()
data["gender"]=le.fit_transform(data["gender"])
print(data.head(20))

       name  hours  score  gender grades class
0     Aarav     10   76.0       1      A    9A
1      Riya      5    NaN       0      A    9B
2     Kabir     10    NaN       1      A   10A
3      Sana      4   55.0       0      C    9A
4    Vivaan      7    NaN       1      B   10B
5    Ishita      6   64.0       0      B    9C
6     Rohan      3   48.0       1      D    9B
7     Meera      9   90.0       0      A   11A
8    Aditya      2   38.0       1      F    9C
9     Kavya     11   93.0       0      A   12A
10    Naman      5   60.0       1      B   10A
11   Jhanvi      7   70.0       0      B   11B
12   Pranav      4   52.0       1      C    9A
13     Tara      9   85.0       0      A   12B
14     Yash      6   66.0       1      B   10C
15    Anaya      8   78.0       0      A   11A
16    Harsh      3   45.0       1      D    9A
17     Diya     10   89.0       0      A   12C
18  Sarthak      6   63.0       1      B   10B
19    Manya      7   74.0       0      B   11B

## Label 2

In [17]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd 
data = pd.read_csv("student_scores.csv")
le = LabelEncoder()
data["gender"]=data["gender"].map({"M" : 1,"F" : 0})
print(data.head(20))

       name  hours  score  gender grades class
0     Aarav     10   76.0       1      A    9A
1      Riya      5    NaN       0      A    9B
2     Kabir     10    NaN       1      A   10A
3      Sana      4   55.0       0      C    9A
4    Vivaan      7    NaN       1      B   10B
5    Ishita      6   64.0       0      B    9C
6     Rohan      3   48.0       1      D    9B
7     Meera      9   90.0       0      A   11A
8    Aditya      2   38.0       1      F    9C
9     Kavya     11   93.0       0      A   12A
10    Naman      5   60.0       1      B   10A
11   Jhanvi      7   70.0       0      B   11B
12   Pranav      4   52.0       1      C    9A
13     Tara      9   85.0       0      A   12B
14     Yash      6   66.0       1      B   10C
15    Anaya      8   78.0       0      A   11A
16    Harsh      3   45.0       1      D    9A
17     Diya     10   89.0       0      A   12C
18  Sarthak      6   63.0       1      B   10B
19    Manya      7   74.0       0      B   11B

In [4]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd 
data = pd.read_csv("student_scores.csv")
le= LabelEncoder()
data["class_encoded"]=le.fit_transform(data["grades"])
X=data[["hours","class_encoded"]]
y=data["score"]

print(X)
print(y)

    hours  class_encoded
0      10              0
1       5              0
2      10              0
3       4              2
4       7              1
..    ...            ...
87      4              2
88     10              0
89      7              1
90      5              2
91      8              0

[92 rows x 2 columns]
0     76.0
1      NaN
2      NaN
3     55.0
4      NaN
      ...
87    52.0
88    88.0
89    73.0
90    57.0
91    81.0
Name: score, Length: 92, dtype: float64

## Normalizing

In [29]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
#load Dataset
data = pd.read_csv("student_scores.csv")
#Encode class column
le=LabelEncoder()
data["class_encoded"]=le.fit_transform(data["grades"])
#Select Features
x=data[["hours","class_encoded"]]
y=data["score"]
#Train/ Test split
x_train, x_test, y_train, y_test = train_test_split(
    x,y, test_size=0.2, random_state=42
)
scaler=StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_train_scaled = scaler.transform(x_test)

### Printing the test , train , split

In [31]:
x_train, x_test, y_train, y_test = train_test_split(
    x,y, test_size=0.2, random_state=42
)
print('X_train shape: ',x_train.shape)
print('X_test shape: ',x_test.shape)
print('y_train shape: ',y_train.shape)
print('y_test shape: ',y_test.shape)
print("Mean: ",x_train_scaled.mean(axis=0))
print("Std: " ,x_train_scaled.std(axis=0))

X_train shape:  (73, 2)
X_test shape:  (19, 2)
y_train shape:  (73,)
y_test shape:  (19,)
Mean:  [-0.12242488  0.16147761]
Std:  [1.08828629 1.1653062 ]

In [39]:
x_train, x_test, y_train, y_test = train_test_split(
    x,y, test_size=0.2
)
x_train

    hours  class_encoded
36      6              1
12      4              2
72      2              4
62      3              3
14      6              1
..    ...            ...
42     10              0
66      5              2
7       9              0
27      3              3
86      8              0

[73 rows x 2 columns]